[package]
name = "compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
derive-where = "1.6.0"
phf = { version = "0.13.1", features = ["macros"] }

[dev-dependencies]
expect-test = "1.5.1"
